# Configuration for the data ingestion pipeline

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion    # Root directory for all data ingestion artifacts
  source_URL: https://github.com/SetuAI/mlpipeline-example/raw/refs/heads/main/data.zip  # URL of the zipped data source
  local_data_file: artifacts/data_ingestion/data.zip # Path to store the downloaded zip file
  raw_data_dir: artifacts/data_ingestion/data        # Directory to store the extracted raw data
  unzip_dir: artifacts/data_ingestion/data        # Directory where the zip file will be extracted (same as raw_data_dir)